name: cytobridge-accept-core
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools=70.3.0
  - libstdcxx-ng>=12
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - scipy
  - pandas
  - h5py
  - pip:
      - pytorch-lightning==2.3.0
      - transformers==4.42.0
      - tokenizers
      - scanpy==1.10.0
      - anndata==0.10.7
      - datasets==2.20.0
      - huggingface-hub==0.23.4
      - pyarrow==16.1.0
      - scikit-misc==0.3.1
      - rdkit==2024.3.3
      - gseapy==1.1.3
      - scikit-learn==1.5.0
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - wandb==0.17.0
      - tqdm
      - pyyaml
      - pytest==8.2.2
      - pytest-cov
      - black
      - isort
      - ruff
